# Generated by Django 5.1.7 on 2025-03-28 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_location', models.CharField(blank=True, max_length=255, null=True)),
                ('saved_expertise', models.CharField(blank=True, max_length=255, null=True)),
                ('min_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('last_searched_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
